<script setup>

</script>

<template>
    <section id="hero" class="block back-black">
        <div id="revslider_gaunte_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="gaunte-landing-page"
             style="background-color: transparent; padding: 0;">
            <div id="revslider_gaunte" class="rev_slider fullscreenbanner" style="display: none;" data-version="5.2.0">
                <ul>
                    <li data-index="rs-gaunte-1" data-transition="fade" data-slotamount="default"
                        data-hideafterloop="0"
                        data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="1000"
                        data-thumb="" data-rotate="0" data-saveperformance="off" data-title="gaunte-1">{# data-param1=""
                        data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7=""
                        data-param8="" data-param9="" data-param10="" data-description="" #}
                        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt=""
                             data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/transparent.png" data-bgposition="center center"
                             data-bgfit="cover" data-bgrepeat="no-repeat" data-bgcolor="#222" class="rev-slidebg"
                             data-no-retina>
                        <div class="tp-caption"
                             id="slide-gaunte-1-layer-1"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['65','40','40','20','20']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['{{ Math.floor(150 * 0.95) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor((150 * 0.66) * 1.12) }}','{{ Math.floor((150 * 0.5) * 1.34) }}']"
                             data-fontsize="['150','{{ Math.floor(150 * 0.87) }}','{{ Math.floor(150 * 0.78) }}','{{ Math.floor(150 * 0.59) }}','{{ Math.floor(150 * 0.42) }}']"
                             data-lineheight="['132','{{ Math.floor(132 * 0.87) }}','{{ Math.floor(132 * 0.78) }}','{{ Math.floor(132 * 0.59) }}','{{ Math.floor(132 * 0.42) }}']"
                             data-fontweight="600"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;s:500;e:Power2.easeIn;s:500;e:Power2.easeIn;"
                             data-start="600"
                             data-splitin="none"
                             data-splitout="none"
                             data-basealign="slide"
                             data-responsive_offset="off"
                             style="z-index: 5; white-space: nowrap; color: rgba(245,245,245, 0.1); font-family: Poppins, Verdana, sans-serif;">
                            A NEW<br>CONCEPT
                        </div>
                        <div class="tp-caption"
                             id="slide-gaunte-1-layer-7"
                             data-x="['right','right','right','right','right']"
                             data-hoffset="['-100','-60','-42','-16','-6']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['-204','-164','-124','-40','0']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:-90deg;s:2500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:45deg;s:1000;e:Power2.easeIn;s:1000;e:Power2.easeIn;"
                             data-start="1200"
                             data-responsive_offset="off"
                             style="z-index: 7;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/coffee_cup.png" alt=""
                            data-ww="['760','760','760','{{ Math.floor(760 * 0.9) }}','{{ Math.floor(760 * 0.6) }}']"
                            data-hh="['1000','1000','1000','{{ Math.floor(1000 * 0.9) }}','{{ Math.floor(1000 * 0.6) }}']"
                            data-no-retina></div>
                        <div class="tp-caption"
                             id="slide-gaunte-1-layer-8"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['-222','-182','-122','-90','-120']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['85','85','67','52','142']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:90deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:-40deg;s:1000;e:Power2.easeIn;s:1000;e:Power2.easeIn;"
                             data-start="900"
                             data-responsive_offset="off"
                             style="z-index: 8;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/wood_pencil2.png" alt=""
                            data-ww="['590','590','590','{{ Math.floor(590 * 0.9) }}','{{ Math.floor(590 * 0.6) }}']"
                            data-hh="['420','420','420','{{ Math.floor(420 * 0.9) }}','{{ Math.floor(420 * 0.6) }}']"
                            data-no-retina></div>
                        <div class="tp-caption"
                             id="slide-gaunte-1-layer-9"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['-13','-13','50','278','260']"
                             data-y="['bottom','bottom','bottom','bottom','bottom']"
                             data-voffset="['22','22','24','-14','-14']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:-45deg;s:1100;e:Power2.easeIn;s:1100;e:Power2.easeIn;"
                             data-start="1100"
                             data-responsive_offset="off"
                             style="z-index: 9;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/eraser_pink.png" alt=""
                            data-ww="['340','340','340','{{ Math.floor(340 * 0.9) }}','{{ Math.floor(340 * 0.6) }}']"
                            data-hh="['180','180','180','{{ Math.floor(180 * 0.9) }}','{{ Math.floor(180 * 0.6) }}']"
                            data-no-retina></div>
                    </li>
                    <li data-index="rs-gaunte-2" data-transition="fade" data-slotamount="default"
                        data-hideafterloop="0"
                        data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="1000"
                        data-thumb="" data-rotate="0" data-saveperformance="off" data-title="gaunte-2" data-param1=""
                        data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7=""
                        data-param8=""
                        data-param9="" data-param10="" data-description="">
                        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                             style='background-color:#555' alt=""
                             data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/transparent.png"
                             data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"
                             data-bgcolor="#555"
                             class="rev-slidebg" data-no-retina>
                        <div class="tp-caption"
                             id="slide-gaunte-2-layer-1"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['65','40','40','20','20']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['{{ Math.floor(150 * 0.95) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor((150 * 0.66) * 1.12) }}','{{ Math.floor((150 * 0.5) * 1.34) }}']"
                             data-fontsize="['150','{{ Math.floor(150 * 0.87) }}','{{ Math.floor(150 * 0.78) }}','{{ Math.floor(150 * 0.59) }}','{{ Math.floor(150 * 0.42) }}']"
                             data-lineheight="['132','{{ Math.floor(132 * 0.87) }}','{{ Math.floor(132 * 0.78) }}','{{ Math.floor(132 * 0.59) }}','{{ Math.floor(132 * 0.42) }}']"
                             data-fontweight="600"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;s:500;e:Power2.easeIn;s:500;e:Power2.easeIn;"
                             data-start="600"
                             data-splitin="none"
                             data-splitout="none"
                             data-basealign="slide"
                             data-responsive_offset="off"
                             style="z-index: 5; white-space: nowrap; color: rgba(0,0,0, 0.2); font-family: Poppins, Verdana, sans-serif;">
                            OBJECTIVE<br>MARKETING
                        </div>
                        <div class="tp-caption"
                             id="slide-gaunte-2-layer-7"
                             data-x="['right','right','right','right','right']"
                             data-hoffset="['-120','-220','-275','-83','-92']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['-60','0','-134','69','113']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:-45deg;s:1100;e:Power2.easeIn;s:1100;e:Power2.easeIn;"
                             data-start="1100"
                             data-basealign="slide"
                             data-responsive_offset="off"
                             style="z-index: 6;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/lamp.png" alt=""
                            data-ww="['750','750','750','{{ Math.floor(750 * 0.7) }}','{{ Math.floor(750 * 0.52) }}']"
                            data-hh="['640','640','640','{{ Math.floor(640 * 0.7) }}','{{ Math.floor(640 * 0.52) }}']"
                            data-no-retina></div>
                        <div class="tp-caption"
                             id="slide-gaunte-2-layer-8"
                             data-x="['left''left','left','left','left']"
                             data-hoffset="['-262','-278','-299','-180','-220']"
                             data-y="['bottom','bottom','bottom','bottom','bottom']"
                             data-voffset="['-12','-12','-42','82','52']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:90deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:-40deg;s:1000;e:Power2.easeIn;s:1000;e:Power2.easeIn;"
                             data-start="900"
                             data-responsive_offset="off"
                             style="z-index: 8;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/plant.png" alt=""
                            data-ww="['750','750','750','{{ Math.floor(750 * 0.7) }}','{{ Math.floor(750 * 0.52) }}']"
                            data-hh="['640','640','640','{{ Math.floor(640 * 0.7) }}','{{ Math.floor(640 * 0.52) }}']"
                            data-no-retina></div>
                    </li>
                    <li data-index="rs-gaunte-3" data-transition="fade" data-slotamount="default"
                        data-hideafterloop="0"
                        data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="1000"
                        data-thumb="" data-rotate="0" data-saveperformance="off" data-title="gaunte-3">{# data-param1=""
                        data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7=""
                        data-param8="" data-param9="" data-param10="" data-description="" #}
                        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                             style='background-color:#ec008c' alt=""
                             data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/transparent.png"
                             data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"
                             data-bgcolor="#ec008c"
                             class="rev-slidebg" data-no-retina>
                        <div class="tp-caption"
                             id="slide-gaunte-3-layer-1"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['65','40','40','20','20']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['{{ Math.floor(150 * 0.95) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor(150 * 0.9) }}','{{ Math.floor((150 * 0.66) * 1.12) }}','{{ Math.floor((150 * 0.5) * 1.34) }}']"
                             data-fontsize="['150','{{ Math.floor(150 * 0.87) }}','{{ Math.floor(150 * 0.78) }}','{{ Math.floor(150 * 0.59) }}','{{ Math.floor(150 * 0.42) }}']"
                             data-lineheight="['132','{{ Math.floor(132 * 0.87) }}','{{ Math.floor(132 * 0.78) }}','{{ Math.floor(132 * 0.59) }}','{{ Math.floor(132 * 0.42) }}']"
                             data-fontweight="600"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;s:500;e:Power2.easeIn;s:500;e:Power2.easeIn;"
                             data-start="600"
                             data-splitin="none"
                             data-splitout="none"
                             data-basealign="slide"
                             data-responsive_offset="off"
                             style="z-index: 5; white-space: nowrap; color: rgba(255,255.255, 0.4); font-family: Poppins, Verdana, sans-serif;">
                            ENGAJEMENT<br>AT CENTER
                        </div>
                        <div class="tp-caption"
                             id="slide-gaunte-3-layer-7"
                             data-x="['right','right','right','left','left']"
                             data-hoffset="['-123','-33','-110','-180','-120']"
                             data-y="['top','top','top','top','top']"
                             data-voffset="['34','34','-27','174','162']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:-90deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:45deg;s:1000;e:Power2.easeIn;s:1000;e:Power2.easeIn;"
                             data-start="1200"
                             data-responsive_offset="off"
                             style="z-index: 7;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/ball.png" alt=""
                            data-ww="['520','520','520','{{ Math.floor(520 * 0.7) }}','{{ Math.floor(520 * 0.45) }}']"
                            data-hh="['380','380','380','{{ Math.floor(380 * 0.7) }}','{{ Math.floor(380 * 0.45) }}']"
                            data-no-retina></div>
                        <div class="tp-caption"
                             id="slide-gaunte-3-layer-8"
                             data-x="['left','left','left','left','left']"
                             data-hoffset="['-300','-340','-283','233','133']"
                             data-y="['bottom','bottom','bottom','bottom','bottom']"
                             data-voffset="['-380','-137','-273','56','96']"
                             data-width="none"
                             data-height="none"
                             data-whitespace="nowrap"
                             data-transform_idle="o:1;"
                             data-transform_in="y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;"
                             data-transform_out="y:top;rZ:-45deg;s:1100;e:Power2.easeIn;s:1100;e:Power2.easeIn;"
                             data-start="1100"
                             data-responsive_offset="off"
                             style="z-index: 9;"><img
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-lazyload="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/img/hero/headphones4.png"
                            alt=""
                            data-ww="['910','910','910','{{ Math.floor(910 * 0.6) }}','{{ Math.floor(910 * 0.5) }}']"
                            data-hh="['800','800','800','{{ Math.floor(800 * 0.6) }}','{{ Math.floor(800 * 0.5) }}']"
                            data-no-retina></div>
                    </li>
                </ul>
                <div style="" class="tp-static-layers">
                    <h2 class="tp-caption tp-static-layer"
                        id="static-gaunte-layer-1"
                        data-x="['left','left','left','left','left']" data-hoffset="['820','512','372','42','32']"
                        data-y="['middle','middle','middle','middle','middle']"
                        data-voffset="['{{ Math.floor(35 * 2) }}','{{ Math.floor(35 * 2.2) }}','{{ Math.floor(35 * 2.2) }}','{{ Math.floor((35 * 0.66) * 3.4) }}','{{ Math.floor((35 * 0.5) * 4.9) }}']"
                        data-fontsize="['{{ Math.floor(35) }}','{{ Math.floor(35) }}','{{ Math.floor(35) }}','{{ Math.floor(35 - 4) }}','{{ Math.floor(35 - 7) }}']"
                        data-lineheight="['{{ Math.floor(35) }}','{{ Math.floor(35) }}','{{ Math.floor(35) }}','{{ Math.floor(35 - 5) }}','{{ Math.floor(35 - 10) }}']"
                        data-fontweight="600"
                        data-width="['410','480','480','480','360']"
                        data-height="none"
                        data-whitespace="nowrap"
                        data-transform_idle="o:1;"
                        data-transform_in="opacity:0;s:500;e:Power2.easeInOut;"
                        data-transform_out="opacity:0;s:300;s:300;"
                        data-start="500"
                        data-splitin="none"
                        data-splitout="none"
                        data-responsive_offset="off"
                        data-startslide="0"
                        data-endslide="2"
                        style="z-index: 21; color: rgba(255,255.255, 1);">One of a kind agency</h2>
                    <div class="tp-caption tp-static-layer"
                         id="static-gaunte-layer-2"
                         data-x="['left','left','left','left','left']"
                         data-hoffset="['822','514','372','44','34']"
                         data-y="['middle','middle','middle','middle','middle']"
                         data-voffset="['{{ Math.floor(35 * 3.8) }}','{{ Math.floor(35 * 4.3) }}','{{ Math.floor(35 * 4.3) }}','{{ Math.floor((35 * 0.7) * 5.8) }}','{{ Math.floor((35 * 0.5) * 8.1) }}']"
                         data-fontsize="none"
                         data-lineheight="none"
                         data-width="['380','480','480','540','360']"
                         data-height="none"
                         data-whitespace="normal"
                         data-transform_idle="o:1;"
                         data-transform_in="opacity:0;s:500;e:Power2.easeInOut;"
                         data-transform_out="opacity:0;s:300;s:300;"
                         data-start="500"
                         data-splitin="none"
                         data-splitout="none"
                         data-responsive_offset="off"
                         data-startslide="0"
                         data-endslide="2"
                         style="z-index: 22; color: rgba(255,255.255, 1);"><p>with a very simple proposal, connect your business to your client.</p></div>
                    <div class="tp-caption tp-static-layer"
                         id="static-gaunte-layer-3"
                         data-x="['left','left','left','left','left']" data-hoffset="['822','514','370','0','0']"
                         data-y="['middle','middle','middle','middle','middle']"
                         data-voffset="['{{ Math.floor(35 * 6) }}','{{ Math.floor(35 * 6.6) }}','{{ Math.floor(35 * 6.6) }}','0','0']"
                         data-width="none"
                         data-height="none"
                         data-whitespace="nowrap"
                         data-transform_idle="o:1;"
                         data-transform_in="opacity:0;s:500;e:Power2.easeInOut;"
                         data-transform_out="opacity:0;s:300;s:300;"
                         data-start="500"
                         data-splitin="none"
                         data-splitout="none"
                         data-responsive_offset="off"
                         data-startslide="0"
                         data-endslide="2"
                         style="z-index: 23; color: rgba(34, 34, 34, 1);">
                        <a href="javascript:void(0)" data-remodal-target="modal_contato"
                           class="sli _mPS2id-h button-effect button--pump button--hero white"
                           onClick="track('hero | contact');">Contact Us</a>
                    </div>
                    <div class="tp-caption tp-static-layer"
                         id="static-gaunte-layer-5"
                         data-x="['left','left','left','left','left']"
                         data-hoffset="['822','514','372','44','34']"
                         data-y="['bottom','bottom','bottom','bottom','bottom']"
                         data-voffset="['30','30','30','28']"
                         data-width="['50','50','50','32','32']"
                         data-height="['50','50','50','32','32']"
                         data-transform_idle="o:1;"
                         data-transform_in="opacity:0;s:500;e:Power2.easeInOut;"
                         data-transform_out="opacity:0;s:300;s:300;"
                         data-start="500"
                         data-splitin="none"
                         data-splitout="none"
                         data-actions='[{"event":"click", "action":"scrollbelow", "offset":"-70px"}]'
                         data-responsive_offset="off"
                         data-visibility="['on', 'off', 'off', 'off']"
                         data-startslide="0"
                         data-endslide="2"
                         style="z-index: 25; width: 50px; height: 50px; cursor: pointer;">
                        <div class="rs-looped rs-slideloop" data-easing="Power2.easeInOut" data-speed="1" data-xs="0"
                             data-xe="0" data-ys="-5" data-ye="5">
                            <img src="https://lwg-assets.s3.us-east-1.amazonaws.com/gaunte/svg/arrow-down-2w.svg" class="svg" alt="">
                        </div>
                    </div>
                </div>
                <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
            </div>
        </div>
    </section>
</template>

<!-- // https://gsap.com/docs/v3/Installation/
     // https://codepen.io/isladjan/pen/abdyPBw -->
