columnSuffix: null
handle: compsShort
instructions: null
name: 'Comps Short'
searchable: false
settings:
  maxBlocks: null
  maxLevels: 4
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  newBlockButtonLabel: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
