name: build

on:
  push:
    branches:
      - main-off
    paths-ignore:
      - '.ddev/**'
      - 'storage/backups/**/*'

jobs:
  backend:
    uses: ./.github/workflows/backend.yml@main
      with:
        dir: 'fantasticdevs'
      secrets: inherit
  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml@main
      with:
        git_env: 'github-pages-prod'
      secrets: inherit

