name: main

on:
  push:
    branches:
      - main-off
    paths-ignore:
      - '.ddev/**'
      - 'storage/backups/**/*'

permissions:
  id-token: write
  contents: read
  actions: read
  pages: write

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    with:
      dir: 'gaunte'
    secrets: inherit
  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      git_env: 'github-pages-main'
    secrets: inherit
