name: build

on:
  push:
    branches:
      - preprod
    paths-ignore:
      - '.ddev/**'
      - 'storage/backups/**/*'

jobs:
  backend:
    uses: ./.github/workflows/backend.yml@preprod
      with:
        dir: 'fantasticdevs-preprod'
      secrets: inherit
  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml@preprod
      with:
        git_env: 'github-pages-preprod'
      secrets: inherit

