name: preprod

on:
  push:
    branches:
      - preprod
    paths-ignore:
      - '.ddev/**'
      - 'storage/backups/**/*'

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    with:
      dir: 'fantasticdevs-preprod'
    secrets: inherit
  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      git_env: 'github-pages-preprod'
    secrets: inherit
